### ISSUE TITLE
Timezone will not change - Password denied

### ISSUE THREAD

**Issue by managerman** [Guilouz/Klipper-Flsun-V400#1]
I went to change my timezone as specified and when I went to change it I received this error about the user not authorized

pi@speeder-pad:~$ sudo timedatectl set-timezone US/Eastern
[sudo] password for pi:
Sorry, user pi is not allowed to execute '/usr/bin/timedatectl set-timezone US/Eastern' as root on speeder-pad.
pi@speeder-pad:~$

**Comment by Guilouz** [comment]
You must enable Root Access first.

**Comment by managerman** [comment]
I did enable the root access....via the update.sh file....I will try it again..  Thanks
