### ISSUE TITLE
Root via update.sh still work?

### ISSUE THREAD

**Issue by arraylabs** [Guilouz/Klipper-Flsun-V400#2]
I'm not having any luck with the update.sh appearing to do anything. Does this method still work with recently delivered printers/speederpads?

**Comment by Guilouz** [comment]
Just fixed this. Re-download zip file.

**Comment by arraylabs** [comment]
Thanks, unfortunately it still doesn't appear to do anything. I'm unable to log into the pad with the provided username and password. I also don't see the .over file on the USB after booting the pad with the stick inserted which kinda implies the update.sh script isn't getting run.

**Comment by Guilouz** [comment]
Try to re-download new zip, it have been updated to set password for pi user to flsun.

**Comment by arraylabs** [comment]
Sorry to say but still no luck. I appreciate your time trying to sort it out.

**Comment by arraylabs** [comment]
Just to confirm where the directions say "root folder" that should be the same level as the cura 4 & 5 installation files, correct?

**Comment by Guilouz** [comment]
Not understand what you mean with Cura.

Root Acess is needed to change time zone, wifi location, klipper etc in SSH, nothing to see with Cura.

**Comment by jFensch** [comment]
I am also experiencing the issue:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/1250152/190536052-a4b29c61-f204-412f-a626-1177e3ad4502.png">

**Comment by Guilouz** [comment]
It seems Flsun have changed something to block root access.

**Comment by Brubrui** [comment]
At night, does the password seem to have changed because flsun is not giving access to the spider pad? Do you know anything about it?. thank you
